qc3:
   /partnerid/12815:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/12730:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/13670:
           product: /COLLEGE_Montana_Grizzlies_T-Shirts/Montana_Grizzlies_Black_Distressed_Logo_T-shirt
   /partnerid/14251:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/10005:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack           
qc2:
   /partnerid/12815:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/12730:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/13670:
           product: /COLLEGE_Montana_Grizzlies_T-Shirts/Montana_Grizzlies_Black_Distressed_Logo_T-shirt
   /partnerid/14251:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/10005:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack           
dev3:
   /partnerid/12815:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/12730:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack
   /partnerid/13670:
           product: /COLLEGE_Montana_Grizzlies_T-Shirts/Montana_Grizzlies_Black_Distressed_Logo_T-shirt
   /partnerid/14251:
           product: /COLLEGE_Montana_Grizzlies_T-Shirts/Montana_Grizzlies_Black_Distressed_Logo_T-shirt
   /partnerid/10005:
           product: /Arizona_Cardinals/on_sale/yes/WinCraft_Arizona_Cardinals_Breast_Cancer_Awareness_Auto_Pack           